= Mastermind: Análisis y Diseño Orientado a Objetos

[.text-center]
[plantuml, diagram-class1, png]
....
title Diagrama de Clases  v1.0
class Main {
    +{static} read: Scanner
    +{static} game: Mastermind
    +{static} main(String[]): void
    +{static} printCombinations(): void
}

class Mastermind {
    -key: String
    -combs: ArrayList<Combination>
    +Mastermind()
    +getKey(): String
    +setKey(): void
    +getCombinations(): ArrayList<Combination>
    +checkCombination(String): boolean
}

class Combination {
    -colors: String
    -dead: int
    -wounded: int
    +Combination()
    +toString(): String
    +getColors(): String
    +setColors(String): void
    +getDead(): int
    +setDead(int): void
    +getWounded(): int
    +setWounded(): void
}

Main --> "0..1" Mastermind
Mastermind --> "0..*" Combination
....

[.text-center]
[plantuml, diagram-class2, png]
....
title Diagrama de Clases  v2.0
class Main {
    +{static} leer: Scanner
    +{static} partida: Mastermind
    +{static} main(String[]): void
    +{static} imprimirPropuestas(): void
}

class Mastermind {
    -colores: String
    -clave: Combinacion
    -propuestas: ArrayList<Combinacion>
    +Mastermind(String)
    +generarClave(): void
    +comprobarPropuesta(String): boolean
    +getPropuestas(): ArrayList<Combinacion>
}

class Combinacion {
    -valor: String
    -muertos: int
    -heridos: int
    +Combinacion()
    +toString(): String
    +getValor(): String
}

Main --> "0..1" Mastermind
Mastermind --> "0..*" Combinacion
....

[.text-center]
[plantuml, diagram-class3, png]
....
title Diagrama de Clases  v3.0

class Mastermind {
	-secretCombination: SecretCombination
	-proposedCombinations: ArrayList<ProposedCombination>
	-results: ArrayList<Result>
	+Mastermind()
	+main(String[]): void
	+play(): void
}

class Combination {
	-colors: ArrayList<Color>
}

class ProposedCombination {
	+read(): void
	+check(): void
}

class SecretCombination {
	+getResult(): void
}

class Result {
	-dead: int
	-wounded: int
	+print(): void
}

enum Color {
	r
	b
	y
	g
	o
	p
}

Mastermind *--> "0..10" ProposedCombination
Mastermind *--> "1" SecretCombination
Mastermind *--> "0..10" Result
Combination *--> "4" Color
Combination <|-- SecretCombination
Combination <|-- ProposedCombination
ProposedCombination <.. SecretCombination
Result <.. SecretCombination
....

[.text-center]
[plantuml, diagram-class4, png]
....
title Diagrama de Clases v4.0

class Mastermind {
	+Mastermind()
	+main(String[]): void
	+play(): void
}

class GameView {
	+GameView(Game)
	+interact(): void
	+retry(): boolean
}

class Game {
	-ATTEMPTS: int
	+Game()
	+addProposedCombination(ProposedCombination): void
	+isFinished(): boolean
	+isWinner(): boolean
	+getResults(): ArrayList<Result>
}

class ProposedCombinationView {
	+ProposedCombinationView()
	+read(): ProposedCombination
}

class Combination {
	-LENGTH: int
	+Combination()
	+getLength(): int
}

class ProposedCombination {
	+ProposedCombination(String)
	+check(): boolean
	+contains(Color,int): boolean
	+contains(Color): boolean
	+getColors(): ArrayList<Color>
}

class SecretCombination {
	+SecretCombination()
	+getResult(ProposedCombination): Result
}

enum Color {
	R: Color
	B: Color
	Y: Color
	G: Color
	O: Color
	P: Color
	color: String
	+Color(String)
	+length(): int
}

class ResultView {
	+ResultView(ArrayList<Result>)
	+print(): void
}

class Result {
	-dead: int
	-wounded: int
	+Result(ProposedCombination,int,int)
	+toString(): String
	+isWinner(): boolean
}

Mastermind *--> "0..1" Game
Mastermind *--> "0..1" GameView
GameView *--> "0..1" Game
ProposedCombination <.. GameView
ResultView <.. GameView
ResultView *--> "0..1" Result
Combination <.. Result
Color <.. SecretCombination
Color <.. ProposedCombination
ProposedCombination *--> "0..1" Result
Game *--> "0..10" ProposedCombination
Game *--> "1" SecretCombination
Game *--> "0..10" Result
Combination *--> "4" Color
Combination <|-- SecretCombination
Combination <|-- ProposedCombination
ProposedCombinationView <.. GameView
ProposedCombination <.. ProposedCombinationView
ProposedCombination <.. SecretCombination
Result <.. SecretCombination
....


[.text-center]
[plantuml, diagram-class5, png]
....
title Diagrama de Clases v5.0

class Mastermind {
	+Mastermind()
	+play(): void
	+main(String[]): void
}

class GameView {
	+GameView(StartController,ProposalController,RetryController)
	+interact(): void
	+start(): void
	+propose(): boolean
	+retry(): boolean
}

class StartView {
	+StartView(StartController)
	+interact(): void
}

class ProposalView {
	+ProposalView(ProposalController)
	+interact(): boolean
}


class RetryView {
	+RetryView(RetryController)
	+interact(): boolean
}

class ProposedCombinationView {
	+ProposedCombinationView(ProposalController)
	+read(): ProposedCombination
}

class ResultView {
	+ResultView(ProposalController)
	+printResults(): void
}

class SecretCombinationView {
	+SecretCombinationView(StartController)
	+interact(): void
}

class Controller {
	+Controller(Game)
}

class StartController {
	+StartController(Game)
	+getLength(): int
}

class ProposalController {
	+ProposalController(Game)
	+addProposedCombination(ProposedCombination): void
	+isFinished(): boolean
	+isWinner(): boolean
	+getResults(): ArrayList<Result>
}

class RetryController {
	+RetryController(Game)
	+retry(): void
}

class Game {
	-ATTEMPTS: int
	+Game()
	+addProposedCombination(ProposedCombination): void
	+isFinished(): boolean
	+isWinner(): boolean
	+getResults(): ArrayList<Result>
	+clear(): void
}

class Combination {
	-LENGTH: int
	+Combination()
	+getLength(): int
}

class ProposedCombination {
	+ProposedCombination(String)
	+check(): boolean
	+contains(Color,int): boolean
	+contains(Color): boolean
	+getColors(): ArrayList<Color>
}

class SecretCombination {
	+SecretCombination()
	+getResult(ProposedCombination): Result
}

enum Color {
	R: Color
	B: Color
	Y: Color
	G: Color
	O: Color
	P: Color
	color: String
	+Color(String)
	+length(): int
}

class Result {
	-dead: int
	-wounded: int
	+Result(ProposedCombination,int,int)
	+toString(): String
	+isWinner(): boolean
}

Mastermind *--> "0..1" ProposalController
Mastermind *--> "0..1" StartController
Mastermind *--> "0..1" RetryController
Mastermind *--> "0..1" GameView
Mastermind *--> "0..1" Game

GameView *--> "0..1" ProposalView
GameView *--> "0..1" StartView
GameView *--> "0..1" RetryView

Controller *--> "0..1" Game
Controller <|-- StartController
Controller <|-- ProposalController
Controller <|-- RetryController

ProposalView *--> "0..1" ProposedCombinationView
ProposalView *--> "0..1" ResultView
ProposalView --> "0..1" ProposalController

StartView *--> "0..1" SecretCombinationView
StartView --> "0..1" StartController

RetryView --> "0..1" RetryController

ProposedCombinationView --> "0..1" ProposalController

ResultView --> "0..1" ProposalController

SecretCombinationView --> "0..1" StartController

Game *--> "0..10" ProposedCombination
Game *--> "1" SecretCombination
Game *--> "0..10" Result

Result *--> "0..1" ProposedCombination

Combination *--> "4" Color
Combination <|-- SecretCombination
Combination <|-- ProposedCombination
....